version: '3.3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=virtualstore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django_web
    env_file:
      - web-variables.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

